### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by pogla** [SiroDiaz/php-klaviyo-api#11]
I think the function `asyncTrack` should be replaced with `asyncTrack` in the readme file.

**Comment by SiroDiaz** [comment]
I see a mistake in the readme file. Do you mean that example code snippet? Anyway i'm going to fix it now.

**Comment by SiroDiaz** [comment]
Fixed. If you see other mistake or something that is wrong feel free to open a new issue or provide a pull request.

**Comment by pogla** [comment]
Will do. Thanks for the fix!
