### ISSUE TITLE
People search - undocumented endpoint

### ISSUE THREAD

**Issue by pogla** [SiroDiaz/php-klaviyo-api#12]
@SiroDiaz I got information about undocumented endpoint:

```
curl -X GET \
  https://a.klaviyo.com/api/v2/people/search \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'api-key: 'YOUR_PRIVATE_KEY' \
  -d '{"email":"test@test.com"}'
```

With this call, it's possible to request a user ID by email.

**Comment by SiroDiaz** [comment]
@pogla I should only allow documented endpoints. But if you want to implement it because it is a must for you, feel free to make a pull request, i will merge it for the next release.
