### ISSUE TITLE
KlaviyoList v2

### ISSUE THREAD

**Issue by Blysq** [SiroDiaz/php-klaviyo-api#3]
Hi I've been working on a project where I need to use the version 2 list API https://www.klaviyo.com/docs/api/v2/lists. 

Currently Siro\Klaviyo\KlaviyoList only supports v1 of the API which is deprecated, however the v1 endpoint is still active. 

Is it worth implementing v2 of the KlaviyoList class to support the V2 endpoint?

**Comment by SiroDiaz** [comment]
Hi @Blysq,
I didn't know that v1 is deprecated. I'm going to upgrade this library to support v2 list API and drop support for v1. Soon or later V1 will be removed and unreachable. I think that in a week 1.2.0 will be available.

**Comment by SiroDiaz** [comment]
1.2.0 has been released. List API v1 has been removed in favour v2. Many methods are the same so changes are minor. Changes are in the response of this API calls. Also 1.2.0 come with your fixes and improved tests for List API.

**Comment by Blysq** [comment]
Great news!

Thanks for responding so quickly. I'm always happy to contribute. 
I should be able to pull this into my project now.

Cheers!

**Comment by SiroDiaz** [comment]
Thank you too. Feel free to colaborate when you need/want. If you have an issue with the new version or related open a new issue.
